- name: Установка и конфигурация Filebeat
  hosts: webservers
  become: yes

  tasks:
    - name: Скачивание Filebeat .deb пакета
      get_url:
        url: https://mirror.yandex.ru/mirrors/elastic/8/pool/main/f/filebeat/filebeat-8.17.4-amd64.deb
        dest: /tmp/filebeat-8.17.4-amd64.deb

    - name: Установка Filebeat
      apt:
        deb: /tmp/filebeat-8.17.4-amd64.deb
        state: present

    - name: Конфигурация filebeat.yml
      copy:
        dest: /etc/filebeat/filebeat.yml
        content: |
          filebeat.inputs:
            - type: log
              enabled: true
              paths:
                - /var/log/nginx/access.log
                - /var/log/nginx/error.log

          output.elasticsearch:
            hosts: ["https://elasticsearch.ru-central1.internal:9200"]
            protocol: https
            username: elastic
            password: cvXCKEl1cfuByxW8NwAF
            ssl.verification_mode: none

          setup.kibana:
            host: "http://kibana.ru-central1.internal:5601"

      notify: restart filebeat

    - name: Включение Filebeat при запуске
      systemd:
        name: filebeat
        enabled: yes
        state: started

  handlers:
    - name: перезапуск filebeat
      systemd:
        name: filebeat
        state: restarted
